import type { Metadata } from "next";
import './globals.css';
import { Header } from "@/components/Common/header";
import { Footer } from "@/components/Common/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`bg-background font-sans min-h-screen flex flex-col sm:gap-25 gap-12.5 text-text`}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
